import type { NextPage } from "next";
import Head from "next/head";

import { MapComp } from "./map-comp";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* mapbox css */}
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>
      <MapComp></MapComp>
    </div>
  );
};

export default Home;
